using System.Globalization;
using BiddingBuddy.Bff.Core.DTOs.Fit;
using BiddingBuddy.Bff.Core.Fit;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

namespace BiddingBuddy.Bff.Infrastructure.Services;

/// <summary>
/// Renders a fit report as the bid/no-bid note a bid manager forwards to their director.
///
/// <para><b>Why this exists at all.</b> An analysis that only lives inside a tab is a demo; one
/// that becomes the internal document is the reason to renew. The decision to chase a tender is
/// approved by someone who will never log in here, and today that person receives a hand-retyped
/// email. This is the same content, already written.</para>
///
/// <para><b>Why .docx rather than PDF.</b> It reuses the OpenXML dependency the grant approval
/// form already pulls in — no new package on a 2 GB box — and, more importantly, the recipient
/// usually wants to add a line before forwarding it. A PDF would force them to retype it, which
/// is the problem this is solving.</para>
///
/// <para>Built from scratch rather than from a template: the number of findings varies per
/// tender, so there is no fixed set of placeholders to fill.</para>
/// </summary>
public static class FitReportDocumentBuilder
{
    private static readonly CultureInfo Inr = CultureInfo.GetCultureInfo("en-IN");

    public static byte[] Build(FitReportDto report, string orgName)
    {
        using var stream = new MemoryStream();
        using (var doc = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
        {
            var main = doc.AddMainDocumentPart();
            main.Document = new Document();
            var body = main.Document.AppendChild(new Body());

            body.AppendChild(Heading("Bid / no-bid note", 28, bold: true));
            body.AppendChild(Text(report.TenderTitle, 22, bold: true));
            body.AppendChild(Text(
                $"Prepared for {orgName} · {report.GeneratedAt.ToLocalTime():dd MMM yyyy HH:mm}", 18,
                italic: true));

            Spacer(body);

            // ── The decision, first. Everything below is the reason for it. ──
            body.AppendChild(Heading("Recommendation", 24));
            body.AppendChild(Text(VerdictLabel(report.Verdict), 24, bold: true));
            body.AppendChild(Text(report.VerdictReason, 20));

            if (!string.IsNullOrWhiteSpace(report.Narrative))
            {
                Spacer(body);
                body.AppendChild(Text(report.Narrative, 20));
                // Labelled in the document too, not only in the app. Whoever receives this may
                // never have seen the screen it came from.
                body.AppendChild(Text("The paragraph above was drafted by AI from the findings below.",
                    16, italic: true));
            }

            // ── What bidding ties up ──
            if (report.Cost.Lines.Count > 0)
            {
                Spacer(body);
                body.AppendChild(Heading("What bidding ties up", 24));
                foreach (var line in report.Cost.Lines)
                    body.AppendChild(Bullet(
                        $"{line.Label}: {(line.IsExempt ? "exempt" : Money(line.Amount))} — {line.Detail}"));
                body.AppendChild(Text(
                    $"Blocked at submission: {Money(report.Cost.BlockedNow)}", 20, bold: true));
            }

            AppendFindings(body, report, FitSeverities.Blocker, "Blockers",
                "These disqualify the bid as things stand.");
            AppendFindings(body, report, FitSeverities.Gap, "Gaps to close",
                "Fixable before the deadline, if started now.");
            AppendFindings(body, report, FitSeverities.Watch, "Worth knowing",
                "Not barriers. They change how the bid should be priced or planned.");
            AppendFindings(body, report, FitSeverities.Unknown, "Not verified",
                "We did not have enough information to check these.");
            AppendFindings(body, report, FitSeverities.Ok, "Checks passed",
                "Verified against the company profile on file.");

            // ── Provenance. A verdict without a rule-set version and a date is an assertion
            //    rather than a record, and this document will outlive the screen. ──
            Spacer(body);
            body.AppendChild(Text(
                $"Generated by Tenders Agent · eligibility rules {report.RuleSetVersion} · "
                + $"{report.GeneratedAt.ToLocalTime():dd MMM yyyy HH:mm}", 16, italic: true));
            body.AppendChild(Text(
                "Findings are computed from the tender's published requirements and the company "
                + "profile on file. Where a requirement could not be checked it is listed as not "
                + "verified rather than assumed to pass.", 16, italic: true));

            main.Document.Save();
        }

        return stream.ToArray();
    }

    private static void AppendFindings(
        Body body, FitReportDto report, string severity, string title, string hint)
    {
        var items = report.Findings.Where(f => f.Severity == severity).ToList();
        if (items.Count == 0) return;

        Spacer(body);
        body.AppendChild(Heading($"{title} ({items.Count})", 24));
        body.AppendChild(Text(hint, 18, italic: true));

        foreach (var f in items)
        {
            body.AppendChild(Bullet(f.Title, bold: true));
            body.AppendChild(Indented(f.Detail));

            if (!string.IsNullOrWhiteSpace(f.Evidence) || !string.IsNullOrWhiteSpace(f.OurPosition))
                body.AppendChild(Indented(
                    $"Tender asks: {f.Evidence ?? "—"}    |    You have: {f.OurPosition ?? "not recorded"}",
                    italic: true));

            // The citation is the point of carrying one: the reader can check the authority
            // rather than take our word for the relaxation.
            if (!string.IsNullOrWhiteSpace(f.Citation))
                body.AppendChild(Indented($"Authority: {f.Citation}", italic: true));
        }
    }

    private static string VerdictLabel(string verdict) => verdict switch
    {
        FitVerdicts.Go               => "GO — nothing checked stands in the way",
        FitVerdicts.GoWithGaps       => "GO WITH GAPS — biddable once the gaps below are closed",
        FitVerdicts.Blocked          => "BLOCKED — cannot bid as things stand",
        FitVerdicts.InsufficientData => "NOT ENOUGH INFORMATION TO SAY",
        _                            => verdict,
    };

    private static string Money(decimal v) => "₹" + v.ToString("N0", Inr);

    // ── OpenXML helpers ─────────────────────────────────────────────────────
    // Direct run properties rather than named styles: a styles part would have to be authored
    // and kept in sync for a document nobody edits as a template.

    private static Paragraph Heading(string text, int halfPoints, bool bold = true) =>
        Text(text, halfPoints, bold, spacingBefore: 240);

    private static Paragraph Text(
        string text, int halfPoints, bool bold = false, bool italic = false, int spacingBefore = 0)
    {
        var props = new RunProperties(new FontSize { Val = halfPoints.ToString(CultureInfo.InvariantCulture) });
        if (bold) props.AppendChild(new Bold());
        if (italic) props.AppendChild(new Italic());

        var paragraph = new Paragraph();
        if (spacingBefore > 0)
            paragraph.AppendChild(new ParagraphProperties(
                new SpacingBetweenLines { Before = spacingBefore.ToString(CultureInfo.InvariantCulture) }));

        paragraph.AppendChild(new Run(props,
            // Preserve is required or Word collapses leading/trailing whitespace in the run.
            new Text(text) { Space = SpaceProcessingModeValues.Preserve }));
        return paragraph;
    }

    private static Paragraph Bullet(string text, bool bold = false)
    {
        // A literal bullet character rather than a numbering part: real list numbering needs a
        // NumberingDefinitionsPart, which is a lot of XML for a visual dash.
        var p = Text("• " + text, 20, bold);
        p.ParagraphProperties ??= new ParagraphProperties();
        p.ParagraphProperties.AppendChild(new Indentation { Left = "360" });
        return p;
    }

    private static Paragraph Indented(string text, bool italic = false)
    {
        var p = Text(text, 18, italic: italic);
        p.ParagraphProperties ??= new ParagraphProperties();
        p.ParagraphProperties.AppendChild(new Indentation { Left = "720" });
        return p;
    }

    private static void Spacer(Body body) => body.AppendChild(new Paragraph(new Run()));
}
